Refactor snapshot, volume naming and update log formats
netbookai/spawner pull request #62
Opened 2022-06-15 14:51 UTC by NishanthSpShetty

# Description

cleanup volume and snapshot names

Fixes # (issue)

Please delete options that are not relevant.

- [x] code refactor/improvements
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# why
- cleaner way to manage snapshot and volume names

# How Has This Been Tested?

- create volume and snapshot

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-15 15:12 UTC, SscSPs requested changes

2022-06-15 15:12 UTC, SscSPs commented on pkg/service/helper/name.go
> +type Kind string
"Kind" is a very generic name for a type, let's try something relatively verbose

2022-06-15 15:16 UTC, NishanthSpShetty commented on pkg/service/azure/volume.go
> +		tags[k] = &v
This pattern is everywhere, so dint add.
Let me see how i can improve this.

Context : when using value in a for loop, the variable is reused and actual realised at the end of loop is what the value of v is. So if we take a pointer to that. The value pointer points in all the tak values will be the last value of the list.
So we are making a shadow of variable to hold the value. 2 things are happening in this place.
1. Copy the value to new variable.
2. Shallow declaration of variable with same name.

2022-06-16 07:52 UTC, NishanthSpShetty commented on pkg/service/azure/volume.go
> +		tags[k] = &v
refactored into a common function in labels.

2022-06-17 15:01 UTC, merged